name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted   # ← faqat shu qator o'zgaradi
    steps:
      - name: Deploy
        run: |
          cd /var/www/IIS
          git pull origin main
          pm2 restart all